"""create initial application schema

Revision ID: d6bba0357aef
Revises: 
Create Date: 2026-08-17 10:52:36.283809
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd6bba0357aef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('cik', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=64), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_cik'), 'companies', ['cik'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_table('filing_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('cik', sa.String(length=16), nullable=False),
    sa.Column('accession_number', sa.String(length=64), nullable=False),
    sa.Column('filing_type', sa.String(length=16), nullable=False),
    sa.Column('filing_date', sa.String(length=16), nullable=True),
    sa.Column('fiscal_period', sa.String(length=32), nullable=True),
    sa.Column('section', sa.String(length=128), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'accession_number', 'section', 'chunk_index')
    )
    op.create_index(op.f('ix_filing_chunks_accession_number'), 'filing_chunks', ['accession_number'], unique=False)
    op.create_index(op.f('ix_filing_chunks_cik'), 'filing_chunks', ['cik'], unique=False)
    op.create_index(op.f('ix_filing_chunks_filing_type'), 'filing_chunks', ['filing_type'], unique=False)
    op.create_index(op.f('ix_filing_chunks_section'), 'filing_chunks', ['section'], unique=False)
    op.create_index(op.f('ix_filing_chunks_ticker'), 'filing_chunks', ['ticker'], unique=False)
    op.create_table('financial_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('period', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('calculated', sa.Boolean(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_metrics_ticker'), 'financial_metrics', ['ticker'], unique=False)
    op.create_table('source_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_metadata_source_type'), 'source_metadata', ['source_type'], unique=False)
    op.create_table('research_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_jobs_ticker'), 'research_jobs', ['ticker'], unique=False)
    op.create_table('graph_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('messages_json', sa.JSON(), nullable=False),
    sa.Column('tool_results_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_traces_ticker'), 'graph_traces', ['ticker'], unique=False)
    op.create_table('provider_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('payload_file_path', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_responses_provider'), 'provider_responses', ['provider'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('report_json', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['research_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_ticker'), 'reports', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_ticker'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_provider_responses_provider'), table_name='provider_responses')
    op.drop_table('provider_responses')
    op.drop_index(op.f('ix_graph_traces_ticker'), table_name='graph_traces')
    op.drop_table('graph_traces')
    op.drop_index(op.f('ix_research_jobs_ticker'), table_name='research_jobs')
    op.drop_table('research_jobs')
    op.drop_index(op.f('ix_source_metadata_source_type'), table_name='source_metadata')
    op.drop_table('source_metadata')
    op.drop_index(op.f('ix_financial_metrics_ticker'), table_name='financial_metrics')
    op.drop_table('financial_metrics')
    op.drop_index(op.f('ix_filing_chunks_ticker'), table_name='filing_chunks')
    op.drop_index(op.f('ix_filing_chunks_section'), table_name='filing_chunks')
    op.drop_index(op.f('ix_filing_chunks_filing_type'), table_name='filing_chunks')
    op.drop_index(op.f('ix_filing_chunks_cik'), table_name='filing_chunks')
    op.drop_index(op.f('ix_filing_chunks_accession_number'), table_name='filing_chunks')
    op.drop_table('filing_chunks')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_cik'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
